version: '2'
networks:
    ssnet:
       ipam:
         config:
         - subnet: 172.28.0.0/24

services:
  redis-master:
    container_name: redis-master
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ssnet
    command: redis-server --appendonly yes

  redis-replica1:
    container_name: redis-replica1
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - ssnet
    command: redis-server --appendonly yes --slaveof redis-master 6379
    
  redis-replica2:
    container_name: redis-replica2
    image: redis:latest
    ports:
      - "6381:6379"
    networks:
      - ssnet
    command: redis-server --appendonly yes --slaveof redis-master 6379

  redis-sentinel_1:
    container_name: redis-sentinel_1
    image: redis:latest
    ports:
      - "26379:26379"
    networks:
      - ssnet
    volumes:
      - ./workmesin2/sentinel/sentinel_1:/data
    command: redis-sentinel /data/sentinel.conf

  redis-sentinel_2:
    container_name: redis-sentinel_2
    image: redis:latest
    ports:
      - "26380:26379"
    networks:
      - ssnet
    volumes:
      - ./workmesin2/sentinel/sentinel_2:/data
    command: redis-sentinel /data/sentinel.conf

  redis-sentinel_3:
    container_name: redis-sentinel_3
    image: redis:latest
    ports:
      - "26381:26379"
    networks:
      - ssnet
    volumes:
      - ./workmesin2/sentinel/sentinel_3:/data
    command: redis-sentinel /data/sentinel.conf
    
  mesin1:
    container_name: mesin-1
    image: royyana/rm-jupyter-go:1.00
    user: root
    ports:
      - "60001:8888"
      - "20001:20000"
    environment:
      - "PASSWORD=mesin1"
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./workmesin1:/home/jovyan/work
      - ./script:/script
    entrypoint: "sh /script/entrypoint.sh"
    #command: "sh /script/entrypoint.sh"
    #entrypoint: "/bin/sh -c 'while true;do sleep 8888;done'"
    networks:
    - ssnet
  mesin2:
    container_name: mesin-2
    image: royyana/rm-jupyter-go:1.00
    user: root
    ports:
      - "60002:8888"
      - "20002:20000"
    environment:
      - "PASSWORD=mesin2"
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./workmesin2:/home/jovyan/work
      - ./script:/script
    entrypoint: "sh /script/entrypoint.sh"
    networks:
    - ssnet
  mesin3:
    container_name: mesin-3
    image: royyana/rm-jupyter-go:1.00
    user: root
    ports:
      - "60003:8888"
      - "20003:20000"
    environment:
      - "PASSWORD=mesin3"
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./workmesin3:/home/jovyan/work
      - ./script:/script
    entrypoint: "sh /script/entrypoint.sh"
    networks:
    - ssnet